Alias:  LNC = http://loinc.org
Alias:  CAT = http://terminology.hl7.org/CodeSystem/observation-category

Instance: Assessment-HH-StartOfCare-FS-6
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-24T14:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Practitioner-LunaBaskins)
* performer[1] = Reference(Role-RN)
* performer[2] = Reference(Org-03)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-03)
* hasMember[0] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-5)
* hasMember[1] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-11)
* hasMember[2] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-17)
* hasMember[3] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-23)
* hasMember[4] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-29)
* hasMember[5] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-35)
* hasMember[6] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-41)
* hasMember[7] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-47)
* hasMember[8] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-53)
* hasMember[9] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-59)
* hasMember[10] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-65)
* hasMember[11] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-71)
* hasMember[12] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-77)
* hasMember[13] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-83)
* hasMember[14] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-89)
* hasMember[15] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-95)
* hasMember[16] = Reference(Assessment-HH-StartOfCare-FS-6-Ob-101)
* derivedFrom = Reference(QResponse-HH-StartOfCare-FS-6)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-SNF-DischargeGoal-FS-4
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-09T15:00:00-05:00"
* code = LNC#85056-0
* code.coding.display = "Mobility - Discharge Goal"
* category = CAT#survey
* performer = Reference(Practitioner-JenCadbury)
* performer[1] = Reference(Role-PT)
* performer[2] = Reference(Org-02)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-02)
* hasMember[0] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-103)
* hasMember[1] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-104)
* hasMember[2] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-105)
* hasMember[3] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-106)
* hasMember[4] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-107)
* hasMember[5] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-108)
* hasMember[6] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-109)
* hasMember[7] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-110)
* hasMember[8] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-111)
* hasMember[9] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-112)
* hasMember[10] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-113)
* hasMember[11] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-114)
* hasMember[12] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-115)
* hasMember[13] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-116)
* hasMember[14] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-117)
* hasMember[15] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-118)
* hasMember[16] = Reference(Assessment-SNF-DischargeGoal-FS-4-Ob-119)
* derivedFrom = Reference(QResponse-SNF-DischargeGoal-FS-4)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-HH-Discharge-FS-7
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-05-01T13:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Practitioner-ScottDumble)
* performer[1] = Reference(Role-RN)
* performer[2] = Reference(Org-03)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-03)
* hasMember[0] = Reference(Assessment-HH-Discharge-FS-7-Ob-6)
* hasMember[1] = Reference(Assessment-HH-Discharge-FS-7-Ob-12)
* hasMember[2] = Reference(Assessment-HH-Discharge-FS-7-Ob-18)
* hasMember[3] = Reference(Assessment-HH-Discharge-FS-7-Ob-24)
* hasMember[4] = Reference(Assessment-HH-Discharge-FS-7-Ob-30)
* hasMember[5] = Reference(Assessment-HH-Discharge-FS-7-Ob-36)
* hasMember[6] = Reference(Assessment-HH-Discharge-FS-7-Ob-42)
* hasMember[7] = Reference(Assessment-HH-Discharge-FS-7-Ob-48)
* hasMember[8] = Reference(Assessment-HH-Discharge-FS-7-Ob-54)
* hasMember[9] = Reference(Assessment-HH-Discharge-FS-7-Ob-60)
* hasMember[10] = Reference(Assessment-HH-Discharge-FS-7-Ob-66)
* hasMember[11] = Reference(Assessment-HH-Discharge-FS-7-Ob-72)
* hasMember[12] = Reference(Assessment-HH-Discharge-FS-7-Ob-78)
* hasMember[13] = Reference(Assessment-HH-Discharge-FS-7-Ob-84)
* hasMember[14] = Reference(Assessment-HH-Discharge-FS-7-Ob-90)
* hasMember[15] = Reference(Assessment-HH-Discharge-FS-7-Ob-96)
* hasMember[16] = Reference(Assessment-HH-Discharge-FS-7-Ob-102)
* derivedFrom = Reference(QResponse-HH-Discharge-FS-7)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-Hospital-Admission-FS-1
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-02T10:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Practitioner-SallySmith)
* performer[1] = Reference(Role-PT)
* performer[2] = Reference(Org-01)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-01)
* extension[device-patient-used][0].valueReference = Reference(Assessment-Hospital-Admission-FS-1-UseOfDevice-1)
* extension[device-patient-used][1].valueReference = Reference(Assessment-Hospital-Admission-FS-1-UseOfDevice-2)
* extension[device-patient-used][2].valueReference = Reference(Assessment-Hospital-Admission-FS-1-UseOfDevice-3)
* hasMember[0] = Reference(Assessment-Hospital-Admission-FS-1-Ob-1)
* hasMember[1] = Reference(Assessment-Hospital-Admission-FS-1-Ob-7)
* hasMember[2] = Reference(Assessment-Hospital-Admission-FS-1-Ob-13)
* hasMember[3] = Reference(Assessment-Hospital-Admission-FS-1-Ob-19)
* hasMember[4] = Reference(Assessment-Hospital-Admission-FS-1-Ob-25)
* hasMember[5] = Reference(Assessment-Hospital-Admission-FS-1-Ob-31)
* hasMember[6] = Reference(Assessment-Hospital-Admission-FS-1-Ob-37)
* hasMember[7] = Reference(Assessment-Hospital-Admission-FS-1-Ob-43)
* hasMember[8] = Reference(Assessment-Hospital-Admission-FS-1-Ob-49)
* hasMember[9] = Reference(Assessment-Hospital-Admission-FS-1-Ob-55)
* hasMember[10] = Reference(Assessment-Hospital-Admission-FS-1-Ob-61)
* hasMember[11] = Reference(Assessment-Hospital-Admission-FS-1-Ob-67)
* hasMember[12] = Reference(Assessment-Hospital-Admission-FS-1-Ob-73)
* hasMember[13] = Reference(Assessment-Hospital-Admission-FS-1-Ob-79)
* hasMember[14] = Reference(Assessment-Hospital-Admission-FS-1-Ob-85)
* hasMember[15] = Reference(Assessment-Hospital-Admission-FS-1-Ob-91)
* hasMember[16] = Reference(Assessment-Hospital-Admission-FS-1-Ob-97)
* derivedFrom = Reference(QResponse-Hospital-Admission-FS-1)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-SNF-Discharge-FS-5
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-23T13:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Practitioner-DanielGranger)
* performer[1] = Reference(Role-RN)
* performer[2] = Reference(Org-02)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-02)
* extension[device-patient-used][0].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-4)
* extension[device-patient-used][1].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-5)
* extension[device-patient-used][2].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-6)
* extension[device-patient-used][3].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-7)
* extension[device-patient-used][4].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-8)
* extension[device-patient-used][5].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-9)
* extension[device-patient-used][6].valueReference = Reference(Assessment-SNF-Discharge-FS-5-UseOfDevice-10)
* hasMember[0] = Reference(Assessment-SNF-Discharge-FS-5-Ob-4)
* hasMember[1] = Reference(Assessment-SNF-Discharge-FS-5-Ob-10)
* hasMember[2] = Reference(Assessment-SNF-Discharge-FS-5-Ob-16)
* hasMember[3] = Reference(Assessment-SNF-Discharge-FS-5-Ob-22)
* hasMember[4] = Reference(Assessment-SNF-Discharge-FS-5-Ob-28)
* hasMember[5] = Reference(Assessment-SNF-Discharge-FS-5-Ob-34)
* hasMember[6] = Reference(Assessment-SNF-Discharge-FS-5-Ob-40)
* hasMember[7] = Reference(Assessment-SNF-Discharge-FS-5-Ob-46)
* hasMember[8] = Reference(Assessment-SNF-Discharge-FS-5-Ob-52)
* hasMember[9] = Reference(Assessment-SNF-Discharge-FS-5-Ob-58)
* hasMember[10] = Reference(Assessment-SNF-Discharge-FS-5-Ob-64)
* hasMember[11] = Reference(Assessment-SNF-Discharge-FS-5-Ob-70)
* hasMember[12] = Reference(Assessment-SNF-Discharge-FS-5-Ob-76)
* hasMember[13] = Reference(Assessment-SNF-Discharge-FS-5-Ob-82)
* hasMember[14] = Reference(Assessment-SNF-Discharge-FS-5-Ob-88)
* hasMember[15] = Reference(Assessment-SNF-Discharge-FS-5-Ob-94)
* hasMember[16] = Reference(Assessment-SNF-Discharge-FS-5-Ob-100)
* derivedFrom = Reference(QResponse-SNF-Discharge-FS-5)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-Hospital-Discharge-FS-2
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-09T14:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Practitioner-RonMarble)
* performer[1] = Reference(Role-PT)
* performer[2] = Reference(Org-01)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-01)
* extension[device-patient-used][0].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-11)
* extension[device-patient-used][1].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-12)
* extension[device-patient-used][2].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-13)
* extension[device-patient-used][3].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-14)
* extension[device-patient-used][4].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-15)
* extension[device-patient-used][5].valueReference = Reference(Assessment-Hospital-Discharge-FS-2-UseOfDevice-16)
* hasMember[0] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-2)
* hasMember[1] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-8)
* hasMember[2] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-14)
* hasMember[3] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-20)
* hasMember[4] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-26)
* hasMember[5] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-32)
* hasMember[6] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-38)
* hasMember[7] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-44)
* hasMember[8] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-50)
* hasMember[9] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-56)
* hasMember[10] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-62)
* hasMember[11] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-68)
* hasMember[12] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-74)
* hasMember[13] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-80)
* hasMember[14] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-86)
* hasMember[15] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-92)
* hasMember[16] = Reference(Assessment-Hospital-Discharge-FS-2-Ob-98)
* derivedFrom = Reference(QResponse-Hospital-Discharge-FS-2)
* derivedFrom.display = "Questionnaire Response"

Instance: Assessment-SNF-Admission-FS-3
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-09T15:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Practitioner-JenCadbury)
* performer[1] = Reference(Role-PT)
* performer[2] = Reference(Org-02)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Org-Loc-02)
* extension[device-patient-used][0].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-17)
* extension[device-patient-used][1].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-18)
* extension[device-patient-used][2].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-19)
* extension[device-patient-used][3].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-20)
* extension[device-patient-used][4].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-21)
* extension[device-patient-used][5].valueReference = Reference(Assessment-SNF-Admission-FS-3-UseOfDevice-22)
* hasMember[0] = Reference(Assessment-SNF-Admission-FS-3-Ob-3)
* hasMember[1] = Reference(Assessment-SNF-Admission-FS-3-Ob-9)
* hasMember[2] = Reference(Assessment-SNF-Admission-FS-3-Ob-15)
* hasMember[3] = Reference(Assessment-SNF-Admission-FS-3-Ob-21)
* hasMember[4] = Reference(Assessment-SNF-Admission-FS-3-Ob-27)
* hasMember[5] = Reference(Assessment-SNF-Admission-FS-3-Ob-33)
* hasMember[6] = Reference(Assessment-SNF-Admission-FS-3-Ob-39)
* hasMember[7] = Reference(Assessment-SNF-Admission-FS-3-Ob-45)
* hasMember[8] = Reference(Assessment-SNF-Admission-FS-3-Ob-51)
* hasMember[9] = Reference(Assessment-SNF-Admission-FS-3-Ob-57)
* hasMember[10] = Reference(Assessment-SNF-Admission-FS-3-Ob-63)
* hasMember[11] = Reference(Assessment-SNF-Admission-FS-3-Ob-69)
* hasMember[12] = Reference(Assessment-SNF-Admission-FS-3-Ob-75)
* hasMember[13] = Reference(Assessment-SNF-Admission-FS-3-Ob-81)
* hasMember[14] = Reference(Assessment-SNF-Admission-FS-3-Ob-87)
* hasMember[15] = Reference(Assessment-SNF-Admission-FS-3-Ob-93)
* hasMember[16] = Reference(Assessment-SNF-Admission-FS-3-Ob-99)
* derivedFrom = Reference(QResponse-SNF-Admission-FS-3)
* derivedFrom.display = "Questionnaire Response"
