Alias:  LNC = http://loinc.org
Alias:  CAT = http://terminology.hl7.org/CodeSystem/observation-category

Instance: Connectathon-Assessment-FS-4-Last3DSNFStay
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-23T13:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-DanielGranger)
* performer[1] = Reference(Connectathon-Role-RN)
* performer[2] = Reference(Connectathon-Org-02)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-02)
* hasMember[0] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-4)
* hasMember[1] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-10)
* hasMember[2] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-16)
* hasMember[3] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-22)
* hasMember[4] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-28)
* hasMember[5] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-34)
* hasMember[6] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-40)
* hasMember[7] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-46)
* hasMember[8] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-52)
* hasMember[9] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-58)
* hasMember[10] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-64)
* hasMember[11] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-70)
* hasMember[12] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-76)
* hasMember[13] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-82)
* hasMember[14] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-88)
* hasMember[15] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-94)
* hasMember[16] = Reference(Connectathon-Assessment-FS-4-Last3DSNFStay-Ob-100)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-4-Last3DSNFStay)
* derivedFrom.display = "Questionnaire Response"

Instance: Connectathon-Assessment-FS-2-Last3DHospStay
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-09T14:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-RonMarble)
* performer[1] = Reference(Connectathon-Role-PT)
* performer[2] = Reference(Connectathon-Org-01)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-01)
* hasMember[0] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-2)
* hasMember[1] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-8)
* hasMember[2] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-14)
* hasMember[3] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-20)
* hasMember[4] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-26)
* hasMember[5] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-32)
* hasMember[6] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-38)
* hasMember[7] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-44)
* hasMember[8] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-50)
* hasMember[9] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-56)
* hasMember[10] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-62)
* hasMember[11] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-68)
* hasMember[12] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-74)
* hasMember[13] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-80)
* hasMember[14] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-86)
* hasMember[15] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-92)
* hasMember[16] = Reference(Connectathon-Assessment-FS-2-Last3DHospStay-Ob-98)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-2-Last3DHospStay)
* derivedFrom.display = "Questionnaire Response"

Instance: Connectathon-Assessment-FS-6-HHDischargePerf
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-05-01T13:00:00-05:00"
* code = LNC#88331-4
* code.coding.display = "Mobility - Discharge Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-ScottDumble)
* performer[1] = Reference(Connectathon-Role-RN)
* performer[2] = Reference(Connectathon-Org-03)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-03)
* hasMember[0] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-6)
* hasMember[1] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-12)
* hasMember[2] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-18)
* hasMember[3] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-24)
* hasMember[4] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-30)
* hasMember[5] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-36)
* hasMember[6] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-42)
* hasMember[7] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-48)
* hasMember[8] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-54)
* hasMember[9] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-60)
* hasMember[10] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-66)
* hasMember[11] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-72)
* hasMember[12] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-78)
* hasMember[13] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-84)
* hasMember[14] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-90)
* hasMember[15] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-96)
* hasMember[16] = Reference(Connectathon-Assessment-FS-6-HHDischargePerf-Ob-102)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-6-HHDischargePerf)
* derivedFrom.display = "Questionnaire Response"

Instance: Connectathon-Assessment-FS-1-First3DHospAdmission
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-02T10:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-SallySmith)
* performer[1] = Reference(Connectathon-Role-PT)
* performer[2] = Reference(Connectathon-Org-01)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-01)
* hasMember[0] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-1)
* hasMember[1] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-7)
* hasMember[2] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-13)
* hasMember[3] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-19)
* hasMember[4] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-25)
* hasMember[5] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-31)
* hasMember[6] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-37)
* hasMember[7] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-43)
* hasMember[8] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-49)
* hasMember[9] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-55)
* hasMember[10] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-61)
* hasMember[11] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-67)
* hasMember[12] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-73)
* hasMember[13] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-79)
* hasMember[14] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-85)
* hasMember[15] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-91)
* hasMember[16] = Reference(Connectathon-Assessment-FS-1-First3DHospAdmission-Ob-97)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-1-First3DHospAdmission)
* derivedFrom.display = "Questionnaire Response"

Instance: Connectathon-Assessment-FS-5-HHStartOfCarePerf
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-24T14:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-LunaBaskins)
* performer[1] = Reference(Connectathon-Role-RN)
* performer[2] = Reference(Connectathon-Org-03)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-03)
* hasMember[0] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-5)
* hasMember[1] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-11)
* hasMember[2] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-17)
* hasMember[3] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-23)
* hasMember[4] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-29)
* hasMember[5] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-35)
* hasMember[6] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-41)
* hasMember[7] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-47)
* hasMember[8] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-53)
* hasMember[9] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-59)
* hasMember[10] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-65)
* hasMember[11] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-71)
* hasMember[12] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-77)
* hasMember[13] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-83)
* hasMember[14] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-89)
* hasMember[15] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-95)
* hasMember[16] = Reference(Connectathon-Assessment-FS-5-HHStartOfCarePerf-Ob-101)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-5-HHStartOfCarePerf)
* derivedFrom.display = "Questionnaire Response"

Instance: Connectathon-Assessment-FS-3-First3DSNFAdmission
InstanceOf: BundledFunctionalStatus
* subject = Reference(patientBSJ1)
* status = #final
* effectiveDateTime = "2020-04-09T15:00:00-05:00"
* code = LNC#88330-6
* code.coding.display = "Mobility - Admission Performance"
* category = CAT#survey
* performer = Reference(Connectathon-Practitioner-JenCadbury)
* performer[1] = Reference(Connectathon-Role-PT)
* performer[2] = Reference(Connectathon-Org-02)
* performer[2].display = "Organization"
* extension[event-location].valueReference = Reference(Connectathon-Org-Loc-02)
* hasMember[0] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-3)
* hasMember[1] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-9)
* hasMember[2] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-15)
* hasMember[3] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-21)
* hasMember[4] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-27)
* hasMember[5] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-33)
* hasMember[6] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-39)
* hasMember[7] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-45)
* hasMember[8] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-51)
* hasMember[9] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-57)
* hasMember[10] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-63)
* hasMember[11] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-69)
* hasMember[12] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-75)
* hasMember[13] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-81)
* hasMember[14] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-87)
* hasMember[15] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-93)
* hasMember[16] = Reference(Connectathon-Assessment-FS-3-First3DSNFAdmission-Ob-99)
* derivedFrom = Reference(Connectathon-QuestResponse-FS-3-First3DSNFAdmission)
* derivedFrom.display = "Questionnaire Response"
